allowed:
  - mit
  - cc0-1.0
  - apache-2.0
  - isc
  - bsd-3-clause
  - bsd-2-clause
manifest:
  exclude:
    - '**/chokidar/**'
sources:
  bower: false
  cabal: false
  go: false
  rubygem: false
reviewed:
  npm:
    - '@webassemblyjs/helper-fsm'
    - '@webassemblyjs/leb128'
    - '@xtuc/ieee754'
    - abab
    - abbrev
    - address
    - array-map
    - array-reduce
    - ast-types-flow
    - atob
    - babel-code-frame
    - babel-generator
    - babel-helpers
    - babel-jest
    - babel-messages
    - babel-plugin-jest-hoist
    - babel-plugin-syntax-object-rest-spread
    - babel-plugin-transform-object-rest-spread
    - babel-preset-jest
    - babel-register
    - babel-runtime
    - babel-template
    - babel-traverse
    - babel-types
    - bcrypt-pbkdf
    - boolbase
    - browserify-zlib
    - bser
    - cacache
    - caniuse-lite
    - capture-exit
    - case-sensitive-paths-webpack-plugin
    - chrome-trace-event
    - color-convert
    - common-tags
    - concat-map
    - core-js-compat
    - css-select
    - damerau-levenshtein
    - dashdash
    - deep-equal
    - deep-is
    - default-gateway
    - detect-node
    - diff
    - doctrine
    - doctrine
    - dom-serializer
    - domain-browser
    - dotenv
    - electron-to-chromium
    - errno
    - escodegen
    - eslint
    - eslint-import-resolver-node
    - eslint-module-utils
    - eslint-plugin-flowtype
    - eslint-scope
    - espree
    - esquery
    - expect
    - fast-json-stable-stringify
    - fb-watchman
    - figgy-pudding
    - file-loader
    - filesize
    - font-awesome
    - fs.realpath
    - get-own-enumerable-property-symbols
    - glob-to-regexp
    - hls.js
    - harmony-reflect
    - hoek
    - http-parser-js
    - http-proxy
    - https-browserify
    - ieee754
    - ignore
    - imurmurhash
    - ipaddr.js
    - is-typedarray
    - isemail
    - istanbul-api
    - istanbul-lib-coverage
    - istanbul-lib-hook
    - istanbul-lib-instrument
    - istanbul-lib-report
    - istanbul-lib-source-maps
    - istanbul-reports
    - jest
    - jest-changed-files
    - jest-cli
    - jest-config
    - jest-diff
    - jest-docblock
    - jest-environment-jsdom
    - jest-environment-node
    - jest-get-type
    - jest-haste-map
    - jest-jasmine2
    - jest-leak-detector
    - jest-matcher-utils
    - jest-message-util
    - jest-mock
    - jest-pnp-resolver
    - jest-regex-util
    - jest-resolve
    - jest-resolve-dependencies
    - jest-runner
    - jest-runtime
    - jest-serializer
    - jest-snapshot
    - jest-util
    - jest-validate
    - jest-watcher
    - jest-worker
    - joi
    - jsbn
    - json-schema
    - json-stable-stringify
    - json-stable-stringify-without-jsonify
    - json3
    - json5
    - json5
    - jsonify
    - left-pad
    - lodash
    - lodash._reinterpolate
    - are-we-there-yet
    - deep-extend
    - fsevents
    - lodash.camelcase
    - lodash.isboolean
    - lodash.isequal
    - lodash.isobject
    - lodash.memoize
    - lodash.sortby
    - lodash.tail
    - lodash.template
    - lodash.templatesettings
    - lodash.uniq
    - m3u8-parser
    - makeerror
    - mdn-data
    - mini-css-extract-plugin
    - minimist
    - minimist
    - minipass
    - minipass
    - minizlib
    - minizlib
    - mkdirp
    - mousetrap
    - nan
    - needle
    - neo-async
    - node-forge
    - node-pre-gyp
    - normalize-package-data
    - npm-bundled
    - npm-bundled
    - npm-packlist
    - optimist
    - pako
    - parse5
    - path-browserify
    - path-is-inside
    - pn
    - pnp-webpack-plugin
    - portfinder
    - postcss-color-gray
    - postcss-load-config
    - postcss-loader
    - pretty-format
    - qs
    - rc
    - rc
    - react-hotkeys
    - react-icons
    - react-transition-group
    - readable-stream
    - readable-stream
    - readdirp
    - regenerator-runtime
    - regenerator-runtime
    - regenerator-transform
    - regjsparser
    - resolve
    - resolve
    - run-queue
    - safe-regex
    - sax
    - saxes
    - serialize-javascript
    - sha.js
    - sockjs
    - sockjs-client
    - source-map
    - source-map
    - spdx-exceptions
    - sprintf-js
    - ssri
    - stack-utils
    - stream-browserify
    - string_decoder
    - stringify-object
    - svgo
    - are-we-there-yet
    - table
    - tar
    - terser
    - text-table
    - through
    - through2
    - timers-browserify
    - tmpl
    - topo
    - ts-pnp
    - tty-browserify
    - tweetnacl
    - typedarray
    - uglify-js
    - uncontrollable
    - uri-js
    - vm-browserify
    - w3c-hr-time
    - w3c-xmlserializer
    - walker
    - warning
    - webpack
    - webpack-dev-middleware
    - webpack-dev-server
    - webpack-log
    - wide-align
    - wordwrap
    - wordwrap
    - workbox-core
    - workbox-navigation-preload
    - workbox-range-requests
    - workbox-strategies
    - workbox-streams
    - worker-farm
    - yargs
    - babel-core
    - babel-core-7.0.0-bridge.0
